# Generated by Django 6.0.2 on 2026-03-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_pedido_detallepedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('nivel_minimo', models.CharField(choices=[('Bronce', 'Bronce'), ('Plata', 'Plata'), ('Oro', 'Oro'), ('VIP', 'VIP')], default='Bronce', help_text='Nivel mínimo del cliente para acceder a la promoción.', max_length=10)),
                ('descuento_porcentaje', models.PositiveIntegerField(help_text='Porcentaje de descuento aproximado que ofrece la promoción.')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
