# Generated by Django 6.0.3 on 2026-03-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_perfil_direccion_perfil_latitud_perfil_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar_estilo',
            field=models.CharField(default='initials', max_length=30),
        ),
        migrations.AddField(
            model_name='perfil',
            name='avatar_semilla',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
